"""Add absence_reason column to Attendance table

Revision ID: 09cd8bd5f75d
Revises: 311f2aece035
Create Date: 2025-06-08 22:26:11.144871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09cd8bd5f75d'
down_revision = '311f2aece035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('absence_reason', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('absence_reason')

    # ### end Alembic commands ###
