"""modifying the Models

Revision ID: 51b0f329393d
Revises: 1d9940de6aaf
Create Date: 2025-06-01 16:03:46.551405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51b0f329393d'
down_revision = '1d9940de6aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.drop_column('username')
        batch_op.drop_column('number')
        batch_op.drop_column('memo')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('leave_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_date', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memo', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('number', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
