"""add table...

Revision ID: cdc988e2c35b
Revises: 
Create Date: 2025-05-30 15:32:09.389050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cdc988e2c35b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('stamp_missing', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('interest', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('leave_date', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('username'))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.TEXT(), nullable=False))
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.drop_column('leave_date')
        batch_op.drop_column('interest')
        batch_op.drop_column('age')
        batch_op.drop_column('join_date')

    op.drop_table('attendance')
    op.drop_table('admin')
    # ### end Alembic commands ###
